const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

function cleanText(value) { return String(value ?? '').replace(/<br\s*\/?>/gi,'\n').replace(/<\/(?:p|div|li|h[1-6]|tr)>/gi,'\n').replace(/<[^>]+>/g,'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/[ \t]+\n/g,'\n').replace(/\n{3,}/g,'\n\n').trim(); }
function keys(){return(process.env.GEMINI_API_KEYS||process.env.GEMINI_API_KEY||'').split(',').map(s=>s.trim()).filter(Boolean);}

function resolveFontPath(){
  const root=path.join(__dirname,'node_modules/@fontsource/noto-sans-sinhala');
  const candidates=[
    path.join(root,'files/noto-sans-sinhala-sinhala-400-normal.ttf'),
    path.join(root,'noto-sans-sinhala-sinhala-400-normal.ttf')
  ];
  for(const p of candidates) if(fs.existsSync(p)&&fs.statSync(p).size>10000)return p;
  const found=[];
  const walk=dir=>{for(const n of fs.readdirSync(dir)){const p=path.join(dir,n);const st=fs.statSync(p);if(st.isDirectory())walk(p);else if(/\.ttf$/i.test(n)&&st.size>10000)found.push(p);}};
  if(fs.existsSync(root))walk(root);
  if(found[0])return found[0];
  throw new Error('Bundled Noto Sans Sinhala TTF is missing. Run npm install.');
}
async function generateStructuredContent(request,args){
  if(args.content&&Array.isArray(args.content.sections))return args.content;
  const pool=keys();if(!pool.length)throw new Error('No Gemini API key configured for document generation');
  const prompt=`You are a document-production planner. Turn the user's request into a print-ready structured document.\n\nUSER REQUEST:\n${request}\n\nReturn ONLY JSON: {"title":"...","subtitle":"...","sections":[{"heading":"...","paragraphs":["..."],"bullets":["..."]}],"table":null,"footer":""}. Preserve requested language, subject, count and style. If the user requests questions or a numbered list, preserve the exact count. No HTML/Markdown/code fences.`;
  let last;for(const key of pool){try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(process.env.GEMINI_TEXT_MODEL||'gemini-2.5-flash')}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:.45,maxOutputTokens:12000}})});const d=await r.json();if(!r.ok)throw new Error(d.error?.message||`Gemini HTTP ${r.status}`);const t=(d.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('').replace(/^```(?:json)?\s*/i,'').replace(/```\s*$/,'').trim();return JSON.parse(t);}catch(e){last=e;}}
  throw last||new Error('Document content generation failed');
}
function palette(style){const s=String(style||'').toLowerCase();if(s.includes('dark'))return{primary:'#172033',accent:'#4F8CFF',text:'#E7ECF5',muted:'#AAB6C8'};if(s.includes('green'))return{primary:'#14532D',accent:'#16A34A',text:'#1F2937',muted:'#64748B'};if(s.includes('purple'))return{primary:'#4C1D95',accent:'#7C3AED',text:'#1F2937',muted:'#64748B'};return{primary:'#173B6C',accent:'#2B6CB0',text:'#1F2937',muted:'#64748B'};}
function renderDocument(data,style,font){return new Promise((resolve,reject)=>{const c=palette(style),doc=new PDFDocument({size:'A4',margin:42,bufferPages:true}),chunks=[];doc.on('data',x=>chunks.push(x));doc.on('error',reject);doc.on('end',()=>resolve(Buffer.concat(chunks)));const W=doc.page.width-84;const header=()=>{doc.save();doc.fillColor(c.primary).rect(0,0,doc.page.width,112).fill();doc.fillColor(c.accent).rect(0,108,doc.page.width,4).fill();doc.fillColor('#fff').font(font).fontSize(21).text(cleanText(data.title||'Document'),42,38,{width:W,align:'center'});if(data.subtitle)doc.fillColor('#DDE7F5').fontSize(10.5).text(cleanText(data.subtitle),42,79,{width:W,align:'center'});doc.restore();doc.y=135;};const footer=n=>{const y=doc.page.height-34;doc.save();doc.strokeColor('#D7DEE8').moveTo(42,y-9).lineTo(doc.page.width-42,y-9).stroke();doc.fillColor(c.muted).font(font).fontSize(8.5).text('Super Agent • Generated document',42,y,{width:260});doc.text(`Page ${n}`,doc.page.width-110,y,{width:68,align:'right'});doc.restore();};doc.font(font);header();for(const s of data.sections||[]){const h=cleanText(s.heading||'');if(h)doc.fillColor(c.primary).fontSize(14).font(font).text(h);for(const p of s.paragraphs||[]){const t=cleanText(p);if(t)doc.fillColor(c.text).fontSize(10.5).font(font).text(t,{lineGap:3,paragraphGap:6});}for(const b of s.bullets||[]){const t=cleanText(b);if(t){doc.fillColor(c.accent).fontSize(10.5).text('•',{continued:true});doc.fillColor(c.text).font(font).text(` ${t}`,{lineGap:2,paragraphGap:3});}}doc.moveDown(.45);}const range=doc.bufferedPageRange();for(let i=range.start;i<range.start+range.count;i++){doc.switchToPage(i);footer(i+1);}doc.end();});}
async function sendTelegram(buffer,filename,caption){const token=process.env.TELEGRAM_BOT_TOKEN,chatId=process.env.NIGHT_AGENT_CHAT_ID;if(!token||!chatId)throw new Error('Telegram credentials are not configured');if(!Buffer.isBuffer(buffer)||buffer.length<1000||buffer.subarray(0,4).toString()!=='%PDF')throw new Error('PDF validation failed before Telegram upload');const fd=new FormData();fd.append('chat_id',chatId);fd.append('caption',caption);fd.append('document',new Blob([buffer],{type:'application/pdf'}),filename);const r=await fetch(`https://api.telegram.org/bot${token}/sendDocument`,{method:'POST',body:fd});const d=await r.json();if(!r.ok||!d.ok||!d.result?.document?.file_id)throw new Error(d.description||`Telegram rejected PDF upload (HTTP ${r.status})`);return{file_id:d.result.document.file_id,message_id:d.result.message_id,chat_id:chatId};}
async function generatePdfDocument(args={}){const request=cleanText(args.request||args.description||args.prompt||'');if(!request&&!args.content)return{created:false,terminal:true,reason:'No document request/content supplied.'};const data=await generateStructuredContent(request,args);const font=resolveFontPath();const pdf=await renderDocument(data,args.style||args.design||'professional',font);const safe=(data.title||'document').replace(/[^a-zA-Z0-9_-]+/g,'_').replace(/^_+|_+$/g,'').slice(0,70)||'document';const filename=`${safe}.pdf`;const delivery=await sendTelegram(pdf,filename,`📄 ${cleanText(data.title||'Document')} — PDF එක සාර්ථකව attach කළා.`);return{created:true,delivered:true,delivery_verified:true,terminal:true,format:'pdf',designed:true,file_name:filename,telegram_file_id:delivery.file_id,telegram_message_id:delivery.message_id,chat_id:delivery.chat_id};}
module.exports={generatePdfDocument};