const fs=require('fs');
const path=require('path');
const os=require('os');
const https=require('https');
const TelegramBot=require('node-telegram-bot-api');
const PDFDocument=require('pdfkit');

const FONT_CACHE_DIR=path.join(os.tmpdir(),'super-agent-fonts');
const FONT_CACHE_PATH=path.join(FONT_CACHE_DIR,'NotoSansSinhala-Regular.ttf');
// Stable raw TTF asset. The previous notofonts.github.io URL was returning
// HTTP 404 in Railway, which was the direct cause of the user's PDF failure.
const FONT_URL=process.env.SINHALA_FONT_URL||'https://raw.githubusercontent.com/notofonts/noto-fonts/main/hinted/ttf/NotoSansSinhala/NotoSansSinhala-Regular.ttf';
const FONT_MIN_BYTES=30000;

function progress(label,state='running'){
  try{const p=global.__nightAgentLiveBridge?.step;return p?Promise.resolve(p(String(label),state)):Promise.resolve();}catch(_){return Promise.resolve();}
}
function clean(s){return String(s??'').replace(/<br\s*\/?>/gi,'\n').replace(/<[^>]*>/g,'').replace(/[ \t]+\n/g,'\n').replace(/\n{3,}/g,'\n\n').trim();}
function jsonOnly(s){return String(s||'').replace(/^```json\s*/i,'').replace(/```$/,'').trim();}
function geminiKeys(){return(process.env.GEMINI_API_KEYS||process.env.GEMINI_API_KEY||'').split(',').map(x=>x.trim()).filter(Boolean);}
function isUsableFont(p){try{return!!p&&fs.existsSync(p)&&fs.statSync(p).size>=FONT_MIN_BYTES;}catch(_){return false;}}
function findLocalFont(dir){if(!fs.existsSync(dir))return null;let entries;try{entries=fs.readdirSync(dir,{withFileTypes:true});}catch(_){return null;}for(const e of entries){const p=path.join(dir,e.name);if(e.isFile()&&/noto.?sans.?sinhala.*\.(ttf|otf)$/i.test(e.name)&&isUsableFont(p))return p;if(e.isDirectory()){const f=findLocalFont(p);if(f)return f;}}return null;}
function findBundledFont(){for(const p of[path.join(__dirname,'assets','fonts','NotoSansSinhala-Regular.ttf'),path.join(__dirname,'fonts','NotoSansSinhala-Regular.ttf'),path.join(__dirname,'NotoSansSinhala-Regular.ttf')])if(isUsableFont(p))return p;try{const root=path.dirname(require.resolve('@fontsource/noto-sans-sinhala/package.json'));return findLocalFont(root);}catch(_){return null;}}
function downloadFont(url,dest,redirects=6){return new Promise((resolve,reject)=>{const req=https.get(url,{headers:{'User-Agent':'Super-Agent-PDF/2.0',Accept:'font/ttf,application/octet-stream,*/*'},timeout:20000},res=>{if([301,302,303,307,308].includes(res.statusCode)&&res.headers.location&&redirects>0){res.resume();return resolve(downloadFont(new URL(res.headers.location,url).toString(),dest,redirects-1));}if(res.statusCode!==200){res.resume();return reject(new Error(`Font download failed: HTTP ${res.statusCode}`));}fs.mkdirSync(path.dirname(dest),{recursive:true});const tmp=`${dest}.part-${process.pid}`;const out=fs.createWriteStream(tmp);res.pipe(out);out.on('finish',()=>out.close(err=>{if(err)return reject(err);try{if(!isUsableFont(tmp))throw new Error(`Downloaded font is invalid/small (${fs.statSync(tmp).size} bytes)`);fs.renameSync(tmp,dest);resolve(dest);}catch(e){try{fs.unlinkSync(tmp);}catch(_){}reject(e);}}));out.on('error',reject);});req.on('timeout',()=>req.destroy(new Error('Sinhala font download timed out')));req.on('error',reject);});}
let fontPromise=null;
async function getFont(){await progress('Sinhala font එක check කරනවා');const local=findBundledFont();if(local){await progress('Sinhala font එක ready','done');return local;}if(isUsableFont(FONT_CACHE_PATH)){await progress('Sinhala font එක cache එකෙන් ගත්තා','done');return FONT_CACHE_PATH;}if(!fontPromise)fontPromise=downloadFont(FONT_URL,FONT_CACHE_PATH).catch(e=>{fontPromise=null;throw new Error(`Sinhala font unavailable: ${e.message}`);});const f=await fontPromise;await progress('Sinhala font එක download කරලා ready','done');return f;}

async function ask(prompt){const keys=geminiKeys();if(!keys.length)throw new Error('No Gemini API key configured for PDF content generation');let last;for(const key of keys){try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(process.env.GEMINI_TEXT_MODEL||'gemini-2.5-flash')}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:.45,maxOutputTokens:8000}})});const d=await r.json();if(!r.ok)throw new Error(d.error?.message||`Gemini HTTP ${r.status}`);return(d.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('');}catch(e){last=e;}}throw last||new Error('Gemini request failed');}

async function makeQuestions(topic,count,language){const result=[],seen=new Set();for(let round=0;result.length<count&&round<25;round++){const need=Math.min(8,count-result.length);await progress(`MCQ ප්‍රශ්න generate කරනවා — ${result.length}/${count}`);const existing=result.slice(-30).map(q=>q.question).join('\n');const raw=await ask(`Create EXACTLY ${need} new high-quality Sri Lankan G.C.E. Advanced Level ICT multiple-choice questions about ${topic}. Language: ${language}. Return ONLY JSON {"questions":[{"question":"...","options":["...","...","...","..."],"answer":"A"}]}. Exactly four distinct options, answer A/B/C/D, exam-quality, no markdown, no duplicates. Existing questions to avoid:\n${existing||'(none)'}`);let data;try{data=JSON.parse(jsonOnly(raw));}catch(_){continue;}for(const q of data.questions||[]){const question=clean(q.question),options=Array.isArray(q.options)?q.options.map(clean):[],answer=String(q.answer||'').trim().toUpperCase(),key=question.toLowerCase().replace(/\s+/g,' ');if(question&&options.length===4&&options.every(Boolean)&&new Set(options.map(x=>x.toLowerCase())).size===4&&/^[ABCD]$/.test(answer)&&!seen.has(key)){seen.add(key);result.push({question,options,answer});}if(result.length>=count)break;}}if(result.length!==count)throw new Error(`Could only generate ${result.length}/${count} valid questions`);await progress(`MCQ ප්‍රශ්න ${count}ම ready`,`done`);return result;}

function designProfile(brief){const b=String(brief||'').toLowerCase();const has=x=>x.some(k=>b.includes(k));const compact=has(['compact','dense','no blank','less blank','wasted','space','අපතේ','හිස් කොල','හිස් පිටු','tight']);const formal=has(['exam','formal','a/l','model paper','question paper','school','විභාග','මොඩල් පේපර්']);const colorful=has(['colorful','colourful','vibrant','bright','වර්ණවත්']);const dark=has(['dark','black','නැඳුරු']);const minimal=has(['minimal','clean','simple','professional','සුදු']);
let primary=dark?'#E5E7EB':colorful?'#0F766E':'#173B6C';let accent=colorful?'#F59E0B':dark?'#64748B':'#27A7A0';let light=dark?'#1F2937':colorful?'#F8FAFC':'#F5F8FC';let option=dark?'#111827':colorful?'#ECFDF5':'#EAF2FF';
return{brief,primary,accent,light,option,compact,formal,colorful,dark,minimal,fontSize:compact?9.5:10.3,optionSize:compact?8.7:9.4,lineGap:compact?0.5:2,margin:compact?34:42};}

function pdfBuffer(title,questions,font,brief){return new Promise((resolve,reject)=>{const d=designProfile(brief);const doc=new PDFDocument({size:'A4',margin:d.margin,bufferPages:true,autoFirstPage:true}),chunks=[];doc.on('data',c=>chunks.push(c));doc.on('error',reject);doc.on('end',()=>resolve(Buffer.concat(chunks)));const W=doc.page.width-d.margin*2;let pageNo=0;
const header=()=>{pageNo++;doc.save();if(!d.dark){doc.fillColor(d.primary).rect(0,0,doc.page.width,d.formal?92:84).fill();doc.fillColor(d.accent).rect(0,d.formal?88:80,doc.page.width,4).fill();doc.fillColor('#fff').font(font).fontSize(d.formal?18:17).text(clean(title),d.margin,27,{width:W,align:'center'});doc.fillColor('#DDEBFF').font(font).fontSize(8.7).text(`A/L ICT • MCQ Model Paper • ${questions.length} Questions`,d.margin,61,{width:W,align:'center'});}else{doc.fillColor(d.primary).rect(0,0,doc.page.width,76).fill();doc.fillColor(d.accent).rect(0,72,doc.page.width,4).fill();doc.fillColor('#fff').font(font).fontSize(17).text(clean(title),d.margin,24,{width:W,align:'center'});}doc.restore();};
const footer=n=>{doc.save();doc.strokeColor(d.dark?'#374151':'#d8dee8').moveTo(d.margin,doc.page.height-30).lineTo(doc.page.width-d.margin,doc.page.height-30).stroke();doc.fillColor(d.dark?'#CBD5E1':'#657184').font(font).fontSize(7.5).text('Super Agent',d.margin,doc.page.height-23);doc.text(`Page ${n}`,doc.page.width-d.margin-60,doc.page.height-23,{width:60,align:'right'});doc.restore();};
const question=(q,i)=>{let y=doc.y;const numW=24;doc.font(font).fontSize(d.fontSize).fillColor(d.primary).text(`${i}.`,d.margin,y,{continued:true,width:numW});doc.font(font).fontSize(d.fontSize).fillColor(d.dark?'#F3F4F6':'#202938').text(` ${q.question}`,{width:W-numW,lineGap:d.lineGap});for(let k=0;k<4;k++){const yy=doc.y+1;const rowH=Math.max(16,doc.heightOfString(q.options[k],{width:W-55,font:font,fontSize:d.optionSize,lineGap:d.lineGap})+6);if(yy+rowH>doc.page.height-48){doc.addPage();header();doc.y=d.dark?96:112;}const y2=doc.y+1;doc.save();doc.fillColor(d.option).roundedRect(d.margin+6,y2,20,rowH,5).fill();doc.restore();doc.font(font).fontSize(d.optionSize).fillColor(d.primary).text('ABCD'[k],d.margin+6,y2+3,{width:20,align:'center'});doc.font(font).fontSize(d.optionSize).fillColor(d.dark?'#F3F4F6':'#374151').text(q.options[k],d.margin+34,y2,{width:W-40,lineGap:d.lineGap});doc.y=y2+rowH+1;}doc.moveDown(.15);};
header();doc.y=d.dark?96:112;for(let i=0;i<questions.length;i++){if(doc.y>doc.page.height-80){doc.addPage();header();doc.y=d.dark?96:112;}question(questions[i],i+1);}
// Do not blindly add a page for the answer key. Reuse remaining space when
// possible; otherwise start a clean new page. This directly fixes the
// wasted/blank-page complaint from the earlier renderer.
const answerRows=Math.ceil(questions.length/4);const answerHeight=65+answerRows*20;let answerY=doc.y;if(answerY+answerHeight>doc.page.height-55){doc.addPage();header();doc.y=d.dark?96:112;answerY=doc.y;}doc.save();doc.fillColor(d.primary).font(font).fontSize(16).text('පිළිතුරු පත්‍රය',d.margin,answerY,{width:W,align:'center'});doc.font(font).fontSize(8).fillColor(d.dark?'#CBD5E1':'#64748B').text('Answer Key',d.margin,answerY+23,{width:W,align:'center'});doc.restore();const startY=answerY+48;const cw=W/4;questions.forEach((q,i)=>{const x=d.margin+(i%4)*cw,y=startY+Math.floor(i/4)*20;doc.save();doc.fillColor(d.light).roundedRect(x+2,y-2,cw-7,16,4).fill();doc.restore();doc.font(font).fontSize(8.5).fillColor(d.primary).text(`${i+1}. ${q.answer}`,x+7,y+1,{width:cw-14});});
const pages=doc.bufferedPageRange();for(let i=pages.start;i<pages.start+pages.count;i++){doc.switchToPage(i);footer(i+1);}doc.end();});}

async function sendPdf(buffer,filename,caption,chatId){await progress('PDF file validate කරනවා');const id=String(chatId||process.env.NIGHT_AGENT_CHAT_ID||'').trim();if(!id)throw new Error('Telegram chat ID is missing');if(!process.env.TELEGRAM_BOT_TOKEN)throw new Error('TELEGRAM_BOT_TOKEN is missing');if(!Buffer.isBuffer(buffer)||buffer.length<1000||buffer.subarray(0,4).toString()!=='%PDF')throw new Error('PDF validation failed before Telegram upload');await progress('Telegram document upload කරනවා');const bot=new TelegramBot(process.env.TELEGRAM_BOT_TOKEN,{polling:false});const msg=await bot.sendDocument(id,buffer,{filename,contentType:'application/pdf'},{caption});if(!msg?.document?.file_id)throw new Error('Telegram did not return a document file_id');await progress('Telegram document delivery confirm උනා','done');return{file_id:msg.document.file_id,message_id:msg.message_id,chat_id:id};}

const completed=new Map();const inflight=new Map();
async function generateDocument(args={}){const count=Math.max(1,Math.min(Number(args.count)||50,100)),topic=clean(args.topic||'Operating Systems'),language=clean(args.language||'Sinhala'),title=clean(args.title||`A/L ICT — ${topic} MCQ Model Paper`),design=clean(args.design||''),chatId=args.chat_id||process.env.NIGHT_AGENT_CHAT_ID,key=JSON.stringify({count,topic,language,title,design,chatId:String(chatId||'')});if(completed.has(key))return{...completed.get(key),duplicate_call:true,terminal:true};if(inflight.has(key))return{...(await inflight.get(key)),duplicate_call:true,terminal:true};const work=(async()=>{await progress('PDF request එක prepare කරනවා');const font=await getFont();await progress('ප්‍රශ්න generate කරනවා');const questions=await makeQuestions(topic,count,language);await progress('User කියපු design brief එක apply කරලා PDF layout කරනවා');const pdf=await pdfBuffer(title,questions,font,design);if(!pdf||pdf.length<1000||pdf.subarray(0,4).toString()!=='%PDF')throw new Error('Generated PDF is empty or invalid');const filename=`AL_ICT_${topic.replace(/[^a-zA-Z0-9]+/g,'_')}_MCQ_${count}.pdf`;const delivery=await sendPdf(pdf,filename,`📄 ${title}\n${count} MCQ questions + answer key`,chatId);const result={created:true,question_count:questions.length,format:'pdf',designed:true,delivered:true,delivery_verified:true,terminal:true,file_name:filename,telegram_file_id:delivery.file_id,telegram_message_id:delivery.message_id,chat_id:delivery.chat_id,design_applied:design||'adaptive default'};completed.set(key,result);return result;})();inflight.set(key,work);try{return await work;}finally{inflight.delete(key);}}
module.exports={generateDocument};
